name: notify

on:
  push:

jobs:
  first-job:
    runs-on: ubuntu-latest
    steps:
      - name: first echo
        run: echo "fisrt"
  second-job:
    runs-on: ubuntu-latest
    steps:
      - name: second echo
        run: echo "second"
  third-job:
    runs-on: ubuntu-latest
    needs: [first-job, second-job]
    steps:
      - name: third echo
        run: echo "third"
#   failure:
#     runs-on: ubuntu-latest
#     steps:
#       - name: failure echo
#         run: go run main.go
