name: notify

on:
  push:

jobs:
  success:
    runs-on: ubuntu-latest
    steps:
      - name: success echo
        run: echo "success 2"
#   failure:
#     runs-on: ubuntu-latest
#     steps:
#       - name: failure echo
#         run: go run main.go
